apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: back
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          env:
            - name: "PG_USER"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: user
            - name: "PG_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: password
            - name: "PG_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database
            - name: "PG_HOSTNAME"
              value: db.data
          image: ghcr.io/do3-2023/mmo-kube/api:v9
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            failureThreshold: 1
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 3
            periodSeconds: 3
      initContainers:
        - name: migration
          env:
            - name: "PG_USER"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: user
            - name: "PG_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: password
            - name: "PG_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database
            - name: "PG_HOSTNAME"
              value: db.data
            - name: "ENV"
              value: "migrate"
            - name: "GIN_MODE"
              value: "release"
          image: ghcr.io/do3-2023/mmo-kube/api:v10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
