apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: back
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      targetPort: 3000
      port: 3000
  type: ClusterIP
