apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: data
spec:
  ports:
    - name: tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP
